#!/bin/sh
set -e

container_role=${CONTAINER_ROLE:-app}
env=${APP_ENV:-production}

cd /var/www/html

echo "Installing composer dependencies..."

if [ "$env" != "production" ]; then
    composer install
else
    composer install --optimize-autoloader --no-dev
fi

if [ "$env" != "local" ]; then
    echo "Caching configuration..."
    php artisan optimize:clear
    php artisan config:cache
    php artisan route:cache
    php artisan view:cache
    php artisan optimize
fi

if [ "$1" != "" ]; then
    exec "$@"

elif [ ${container_role} = "app" ]; then
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.app.conf

elif [ ${container_role} = "queue" ]; then
    echo "*/1 * * * * php /var/www/html/artisan schedule:run --verbose --no-interaction" > /etc/supercronic/laravel
    exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.queue.conf

else
    echo "Container mode mismatched."
    exit 1
fi


